kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: test-app
  namespace: test
  labels:
    app: test-app
    app.kubernetes.io/component: test-app
    app.kubernetes.io/instance: test-app
    app.kubernetes.io/name: test-app
    app.kubernetes.io/part-of: s-2-i-git-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-app
        deployment: test-app
    spec:
      containers:
        - name: test-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/test/test-app@sha256:7317cd4c38baa632d0173281f862a0638b2a9772b475fcb5c04ba3a3abf689e7
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - CAP_NET_BIND_SERVICE
            privileged: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: httpd
      serviceAccount: httpd
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
